gandi: update logic to allow updating IPv6/AAAA
ddclient/ddclient pull request #558
Opened 2023-08-01 03:07 UTC by TinfoilSubmarine

2023-08-01 18:12 UTC, LenardHess commented
When using `wantipv4/wantipv6`, the provider implementation has to then set `status-ipv4/status-ipv6` instead of `status`, `ipv4/ipv6` instead of `ip` and so on.

I admit the rules for this aren't clearly written down yet, we went over some details in this pull request (while in a fork, so other repo): https://github.com/rrthomas/ddclient/pull/10

2023-08-01 21:54 UTC, TinfoilSubmarine commented
Is this better? I also added skipping the update if the record is already set to the same IP.

2023-08-10 13:34 UTC, TinfoilSubmarine commented
FYI, I'm done making revisions on this.

2023-08-12 14:00 UTC, LenardHess commented
Thanks for the update (again :wink:)

We will leave this pull request open until v3.11.0 has been released (see https://github.com/ddclient/ddclient/issues/552#issuecomment-1675925270 for details). It will get pulled into v3.11.1

2023-10-21 18:04 UTC, LenardHess commented
Same as #557 - please rebase onto master for the merge.

2023-10-25 19:23 UTC, TinfoilSubmarine commented on ddclient.in
> +  ttl=360 # optional
thanks, updated

2023-11-19 18:40 UTC, LenardHess requested changes
There is a few things i still noticed - Apologies for not noticing them the first time around.
The "Nitpick" stuff isn't urgent, feel free to skip those suggestions.

2023-11-19 18:40 UTC, LenardHess commented on ddclient.in
> +            if($response->{'rrset_values'}->[0] eq $ip) {
This should also check the TTL

2023-11-19 18:40 UTC, LenardHess commented on ddclient.in
> +                next;
This has to set 'status-ipv*', 'ipv*' and 'mtime' to properly let ddclient cache/avoid redundant update checks.

2023-11-25 12:54 UTC, LenardHess approved these changes
Looks good :+1:

2023-11-25 12:55 UTC, merged